/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pawnsystem;

import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author macbookpro14
 */
public class Dashboard extends javax.swing.JFrame {

    String tempName="";
    String tempRole = "";
    int tempId = 0;
    String tempUsername ="";
    String tempPassword="";
    /**
     * Creates new form Dashboard
     */
    public Dashboard(int id, String name, String username, String password, String role) {
        initComponents();
        setTitle("JTam Pawnshop");
        setResizable(false);
        MainPanel mPanel = new MainPanel();
        dashboardPanel.removeAll();
        dashboardPanel.add(mPanel.mainPanel);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
        dashboardPanel.updateUI();
        labelName.setText(name);
        
        tempName = name;
        tempRole = role;
        tempId = id;
        tempUsername = username;
        tempPassword = password;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        lhome = new javax.swing.JLabel();
        loanPanel = new javax.swing.JPanel();
        lloan = new javax.swing.JLabel();
        redeemPanel = new javax.swing.JPanel();
        lredeem = new javax.swing.JLabel();
        pawnPanel = new javax.swing.JPanel();
        lpawn = new javax.swing.JLabel();
        logoutPanel = new javax.swing.JPanel();
        llogout = new javax.swing.JLabel();
        reportPanel = new javax.swing.JPanel();
        lreport = new javax.swing.JLabel();
        staffPanel = new javax.swing.JPanel();
        lstaff = new javax.swing.JLabel();
        inventoryPanel = new javax.swing.JPanel();
        linventory = new javax.swing.JLabel();
        dashboardPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(75, 84, 92));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setFont(new java.awt.Font("Baloo Bhai 2", 1, 20)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-36.png"))); // NOI18N
        labelName.setText("Username");
        labelName.setIconTextGap(10);
        mainPanel.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jSeparator3.setForeground(new java.awt.Color(114, 116, 122));
        mainPanel.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 73, 250, -1));

        jSeparator1.setForeground(new java.awt.Color(114, 116, 122));
        mainPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 138, 220, -1));

        jLabel3.setFont(new java.awt.Font("Baloo Bhai 2", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PawnShop");
        jLabel3.setIconTextGap(10);
        mainPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, -1));

        homePanel.setBackground(new java.awt.Color(75, 84, 92));
        homePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homePanelMousePressed(evt);
            }
        });
        homePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lhome.setFont(new java.awt.Font("Baloo Bhai 2", 1, 16)); // NOI18N
        lhome.setForeground(new java.awt.Color(194, 199, 208));
        lhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-18.png"))); // NOI18N
        lhome.setText("Home");
        lhome.setIconTextGap(10);
        homePanel.add(lhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        mainPanel.add(homePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 50));

        loanPanel.setBackground(new java.awt.Color(75, 84, 92));
        loanPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loanPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loanPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                loanPanelMousePressed(evt);
            }
        });
        loanPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lloan.setFont(new java.awt.Font("Baloo Bhai 2", 1, 16)); // NOI18N
        lloan.setForeground(new java.awt.Color(194, 199, 208));
        lloan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-loan-18.png"))); // NOI18N
        lloan.setText("Loan");
        lloan.setIconTextGap(10);
        loanPanel.add(lloan, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        mainPanel.add(loanPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 50));

        redeemPanel.setBackground(new java.awt.Color(75, 84, 92));
        redeemPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                redeemPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                redeemPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                redeemPanelMousePressed(evt);
            }
        });
        redeemPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lredeem.setFont(new java.awt.Font("Baloo Bhai 2", 1, 16)); // NOI18N
        lredeem.setForeground(new java.awt.Color(194, 199, 208));
        lredeem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-money-loan-18.png"))); // NOI18N
        lredeem.setText("Redeem");
        lredeem.setIconTextGap(10);
        redeemPanel.add(lredeem, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        mainPanel.add(redeemPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 50));

        pawnPanel.setBackground(new java.awt.Color(75, 84, 92));
        pawnPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pawnPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pawnPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pawnPanelMousePressed(evt);
            }
        });
        pawnPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lpawn.setFont(new java.awt.Font("Baloo Bhai 2", 1, 16)); // NOI18N
        lpawn.setForeground(new java.awt.Color(194, 199, 208));
        lpawn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-pawnbroker-18.png"))); // NOI18N
        lpawn.setText("Pawn");
        lpawn.setIconTextGap(10);
        pawnPanel.add(lpawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        mainPanel.add(pawnPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 50));

        logoutPanel.setBackground(new java.awt.Color(255, 51, 51));
        logoutPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logoutPanelMousePressed(evt);
            }
        });
        logoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        llogout.setFont(new java.awt.Font("Baloo Bhai 2", 1, 16)); // NOI18N
        llogout.setForeground(new java.awt.Color(255, 255, 255));
        llogout.setText("Logout");
        llogout.setIconTextGap(10);
        logoutPanel.add(llogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        mainPanel.add(logoutPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 200, 50));

        reportPanel.setBackground(new java.awt.Color(75, 84, 92));
        reportPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                reportPanelMousePressed(evt);
            }
        });
        reportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lreport.setFont(new java.awt.Font("Baloo Bhai 2", 1, 16)); // NOI18N
        lreport.setForeground(new java.awt.Color(194, 199, 208));
        lreport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-report-18 (1).png"))); // NOI18N
        lreport.setText("Pawn HIstory");
        lreport.setIconTextGap(10);
        reportPanel.add(lreport, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        mainPanel.add(reportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 200, 50));

        staffPanel.setBackground(new java.awt.Color(75, 84, 92));
        staffPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                staffPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                staffPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffPanelMousePressed(evt);
            }
        });
        staffPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstaff.setFont(new java.awt.Font("Baloo Bhai 2", 1, 16)); // NOI18N
        lstaff.setForeground(new java.awt.Color(194, 199, 208));
        lstaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-staff-18.png"))); // NOI18N
        lstaff.setText("Staff Account");
        lstaff.setIconTextGap(10);
        staffPanel.add(lstaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        mainPanel.add(staffPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 200, 50));

        inventoryPanel.setBackground(new java.awt.Color(75, 84, 92));
        inventoryPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inventoryPanelMousePressed(evt);
            }
        });
        inventoryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linventory.setFont(new java.awt.Font("Baloo Bhai 2", 1, 16)); // NOI18N
        linventory.setForeground(new java.awt.Color(194, 199, 208));
        linventory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-box-18.png"))); // NOI18N
        linventory.setText("Inventory");
        linventory.setIconTextGap(10);
        inventoryPanel.add(linventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        mainPanel.add(inventoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 50));

        dashboardPanel.setPreferredSize(new java.awt.Dimension(830, 720));

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inventoryPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryPanelMouseEntered
        // TODO add your handling code here:\
        inventoryPanel.setBackground(new Color(103, 116, 128));
        linventory.setForeground(Color.white);
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-box-18 (1).png");
        linventory.setIcon(img);
    }//GEN-LAST:event_inventoryPanelMouseEntered

    private void inventoryPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryPanelMouseExited
        // TODO add your handling code here:
        inventoryPanel.setBackground(new Color(75,84,92));
        linventory.setForeground(new Color(194,199,208));
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-box-18.png");
        linventory.setIcon(img);
    }//GEN-LAST:event_inventoryPanelMouseExited

    private void homePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseEntered
        // TODO add your handling code here:
        homePanel.setBackground(new Color(103, 116, 128));
        lhome.setForeground(Color.white);
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-home-18 (1).png");
        lhome.setIcon(img);
    }//GEN-LAST:event_homePanelMouseEntered

    private void homePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMouseExited
        // TODO add your handling code here:
        homePanel.setBackground(new Color(75,84,92));
        lhome.setForeground(new Color(194,199,208));
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-home-18.png");
        lhome.setIcon(img);
    }//GEN-LAST:event_homePanelMouseExited

    private void loanPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanPanelMouseEntered
        // TODO add your handling code here:
        loanPanel.setBackground(new Color(103, 116, 128));
        lloan.setForeground(Color.white);
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-loan-18 (1).png");
        lloan.setIcon(img);
    }//GEN-LAST:event_loanPanelMouseEntered

    private void loanPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanPanelMouseExited
        // TODO add your handling code here:
        loanPanel.setBackground(new Color(75,84,92));
        lloan.setForeground(new Color(194,199,208));
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-loan-18.png");
        lloan.setIcon(img);
    }//GEN-LAST:event_loanPanelMouseExited

    private void redeemPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redeemPanelMouseEntered
        // TODO add your handling code here:
        redeemPanel.setBackground(new Color(103, 116, 128));
        lredeem.setForeground(Color.white);
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-money-loan-18 (1).png");
        lredeem.setIcon(img);
    }//GEN-LAST:event_redeemPanelMouseEntered

    private void redeemPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redeemPanelMouseExited
        // TODO add your handling code here:
        redeemPanel.setBackground(new Color(75,84,92));
        lredeem.setForeground(new Color(194,199,208));
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-money-loan-18.png");
        lredeem.setIcon(img);
    }//GEN-LAST:event_redeemPanelMouseExited

    private void pawnPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pawnPanelMouseEntered
        // TODO add your handling code here:
        pawnPanel.setBackground(new Color(103, 116, 128));
        lpawn.setForeground(Color.white);
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-pawnbroker-18 (1).png");
        lpawn.setIcon(img);
    }//GEN-LAST:event_pawnPanelMouseEntered

    private void pawnPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pawnPanelMouseExited
        // TODO add your handling code here:
        pawnPanel.setBackground(new Color(75,84,92));
        lpawn.setForeground(new Color(194,199,208));
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-pawnbroker-18.png");
        lpawn.setIcon(img);
    }//GEN-LAST:event_pawnPanelMouseExited

    private void staffPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffPanelMouseEntered
        // TODO add your handling code here:
        staffPanel.setBackground(new Color(103, 116, 128));
        lstaff.setForeground(Color.white);
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-staff-18 (1).png");
        lstaff.setIcon(img);
    }//GEN-LAST:event_staffPanelMouseEntered

    private void staffPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffPanelMouseExited
        // TODO add your handling code here:
        staffPanel.setBackground(new Color(75,84,92));
        lstaff.setForeground(new Color(194,199,208));
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-staff-18.png");
        lstaff.setIcon(img);
    }//GEN-LAST:event_staffPanelMouseExited

    private void logoutPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseEntered
        // TODO add your handling code here:
        logoutPanel.setBackground(new Color(204, 43, 43));
        llogout.setForeground(Color.white);      
    }//GEN-LAST:event_logoutPanelMouseEntered

    private void logoutPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseExited
        // TODO add your handling code here:
        logoutPanel.setBackground(new Color(255,51,51));
        llogout.setForeground(Color.white);  
    }//GEN-LAST:event_logoutPanelMouseExited

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        // TODO add your handling code here:
        logoutPanel.setBackground(new Color(150, 30, 30));
        llogout.setForeground(Color.white);
        Login login = new Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_logoutPanelMouseClicked

    private void reportPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMouseEntered
        // TODO add your handling code here:
        reportPanel.setBackground(new Color(103, 116, 128));
        lreport.setForeground(Color.white);
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-report-18 (1).png");
        lreport.setIcon(img);
    }//GEN-LAST:event_reportPanelMouseEntered

    private void reportPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMouseExited
        // TODO add your handling code here:
        reportPanel.setBackground(new Color(75,84,92));
        lreport.setForeground(new Color(194,199,208));
        ImageIcon img = new ImageIcon("/Users/macbookpro14/Desktop/Fake Desktop/SETEC/Year 4/Java with IReport/PawnSystem/src/images/icons8-report-18.png");
        lreport.setIcon(img);
    }//GEN-LAST:event_reportPanelMouseExited

    private void logoutPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMousePressed
        // TODO add your handling code here:
        Login login = new Login();
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_logoutPanelMousePressed

    private void homePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanelMousePressed
        // TODO add your handling code here:
        MainPanel mPanel = new MainPanel();
        dashboardPanel.removeAll();
        dashboardPanel.add(mPanel.mainPanel);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
        dashboardPanel.updateUI();
    }//GEN-LAST:event_homePanelMousePressed

    private void staffPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffPanelMousePressed
        // TODO add your handling code here:
        if(tempRole.equalsIgnoreCase("admin")){
            Staff st = new Staff();
            dashboardPanel.removeAll();
            dashboardPanel.add(st.jPanel1);
            dashboardPanel.revalidate();
            dashboardPanel.repaint();
            dashboardPanel.updateUI();
        }else{
            StaffForUser st = new StaffForUser(tempId,tempName,tempUsername,tempPassword,tempRole);
            dashboardPanel.removeAll();
            dashboardPanel.add(st.jPanel1);
            dashboardPanel.revalidate();
            dashboardPanel.repaint();
            dashboardPanel.updateUI();
        }
        
    }//GEN-LAST:event_staffPanelMousePressed

    private void pawnPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pawnPanelMousePressed
        // TODO add your handling code here:
        Pawn p = new Pawn(0);
        dashboardPanel.removeAll();
        dashboardPanel.add(p.jPanel1);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
        dashboardPanel.updateUI();
        if(tempRole.equals("Clerk")){
            p.btnMoreInterest.setEnabled(false);
        }
    }//GEN-LAST:event_pawnPanelMousePressed

    private void loanPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loanPanelMousePressed
        // TODO add your handling code here:
        Loan l = new Loan();
        dashboardPanel.removeAll();
        dashboardPanel.add(l.jPanel1);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
        dashboardPanel.updateUI();
    }//GEN-LAST:event_loanPanelMousePressed

    private void inventoryPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryPanelMousePressed
        // TODO add your handling code here:
            Inventory inv = new Inventory();
            dashboardPanel.removeAll();
            dashboardPanel.add(inv.jPanel1);
            dashboardPanel.revalidate();
            dashboardPanel.repaint();
            dashboardPanel.updateUI();
            if(tempRole.equals("Clerk")){
                inv.btnupdate.setEnabled(false);
            }   
    }//GEN-LAST:event_inventoryPanelMousePressed

    private void redeemPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_redeemPanelMousePressed
        // TODO add your handling code here:
        Redeem red = new Redeem();
        dashboardPanel.removeAll();
        dashboardPanel.add(red.jPanel1);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
        dashboardPanel.updateUI();
    }//GEN-LAST:event_redeemPanelMousePressed

    private void reportPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportPanelMousePressed
        // TODO add your handling code here:
        PawnHistory ph = new PawnHistory();
        dashboardPanel.removeAll();
        dashboardPanel.add(ph.jPanel1);
        dashboardPanel.revalidate();
        dashboardPanel.repaint();
        dashboardPanel.updateUI();
         if(tempRole.equals("Clerk")){
                ph.btnclear.setEnabled(false);
        }   
    }//GEN-LAST:event_reportPanelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel(new FlatIntelliJLaf());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard(0,"kakda","kakda","123","admin").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JDesktopPane dashboardPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JPanel inventoryPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel lhome;
    private javax.swing.JLabel linventory;
    private javax.swing.JLabel lloan;
    private javax.swing.JLabel llogout;
    private javax.swing.JPanel loanPanel;
    private javax.swing.JPanel logoutPanel;
    private javax.swing.JLabel lpawn;
    private javax.swing.JLabel lredeem;
    private javax.swing.JLabel lreport;
    private javax.swing.JLabel lstaff;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel pawnPanel;
    private javax.swing.JPanel redeemPanel;
    private javax.swing.JPanel reportPanel;
    public javax.swing.JPanel staffPanel;
    // End of variables declaration//GEN-END:variables
}
